README.md, src/Kreta/Bundle/WebBundle/Resources/public/scss/component/issue/_issue-comment.scss, src/Kreta/Bundle/WebBundle/Resources/public/scss/component/issue/_issue-vcs.scss, src/Kreta/Bundle/WebBundle/Resources/public/scss/component/issue/_issue.scss, src/Kreta/Bundle/WebBundle/Resources/public/scss/component/issue/_mini-issue.scss, src/Kreta/Bundle/WebBundle/Resources/public/scss/component/notification/_notification.scss, src/Kreta/Bundle/WebBundle/Resources/public/scss/component/project/_mini-project.scss, src/Kreta/Bundle/WebBundle/Resources/public/scss/component/project/_project-users.scss, src/Kreta/Bundle/WebBundle/Resources/public/scss/element/_flash.scss, src/Kreta/Bundle/WebBundle/Resources/public/scss/element/_icon-item.scss, src/Kreta/Bundle/WebBundle/Resources/public/scss/element/_image-preview.scss, src/Kreta/Bundle/WebBundle/Resources/public/scss/layout/_header.scss, src/Kreta/Bundle/WebBundle/Resources/public/scss/layout/_landing.scss, src/Kreta/Bundle/WebBundle/Resources/public/scss/layout/_widget.scss, src/Kreta/Bundle/WebBundle/gulpfile.js, src/Kreta/Bundle/WebBundle/package.json
- Compass's CSS3 cross-browser is changed for gulp-autoprefixer task
=> Removed compass dependency for frontend development

phpspec.yml, src/Kreta/SharedKernel/Domain/Model/Id.php, src/Kreta/SharedKernel/Domain/Model/Uuid.php, src/Kreta/SharedKernel/Tests/Double/Domain/Model/AggregateRootStub.php, src/Kreta/TaskManager/Domain/Model/Organization/Organization.php, src/Kreta/TaskManager/Domain/Model/Organization/OrganizationId.php, src/Kreta/TaskManager/Domain/Model/Organization/OrganizationParticipant.php, src/Kreta/TaskManager/Domain/Model/Organization/OrganizationParticipantId.php, src/Kreta/TaskManager/Domain/Model/Organization/Owner.php, src/Kreta/TaskManager/Domain/Model/Organization/OwnerId.php, src/Kreta/TaskManager/Domain/Model/Organization/Participant.php, src/Kreta/TaskManager/Domain/Model/Organization/ParticipantId.php, src/Kreta/TaskManager/Domain/Model/Project/Project.php, src/Kreta/TaskManager/Domain/Model/Project/ProjectId.php, src/Kreta/TaskManager/Domain/Model/Project/Task/Task.php, src/Kreta/TaskManager/Domain/Model/Project/Task/TaskId.php, src/Kreta/TaskManager/Domain/Model/User/UserId.php, src/Kreta/TaskManager/Tests/Double/Domain/Model/ParticipantIdStub.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Organization/OrganizationIdSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Organization/OrganizationParticipantIdSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Organization/OrganizationParticipantSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Organization/OrganizationSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Organization/OwnerIdSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Organization/OwnerSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Organization/ParticipantIdSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/ProjectIdSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/ProjectSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/Task/TaskIdSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/Task/TaskSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/User/UserIdSpec.php
=> Added initial domain model of organization project and user submodules

composer.json, src/Kreta/SharedKernel/Domain/Model/Slug.php, src/Kreta/SharedKernel/Tests/Spec/Kreta/SharedKernel/Domain/Model/SlugSpec.php, src/Kreta/TaskManager/Domain/Model/Organization/Organization.php, src/Kreta/TaskManager/Domain/Model/Organization/OrganizationName.php, src/Kreta/TaskManager/Domain/Model/Organization/OrganizationNameEmptyException.php, src/Kreta/TaskManager/Domain/Model/Organization/OrganizationSlug.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Organization/OrganizationNameEmptyExceptionSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Organization/OrganizationNameSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Organization/OrganizationSlugSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Organization/OrganizationSpec.php
| Doc PR        | reference to the documentation PR, if any
* Added organization name
* Check organization name is never empty
* Added Slug in SharedKernel
* Implemented Slug in OrganizationSlug
=> Added new organization properties

phpspec.yml, src/Kreta/SharedKernel/Tests/Matchers/CollectionMatcher.php, src/Kreta/TaskManager/Domain/Model/Organization/Organization.php, src/Kreta/TaskManager/Domain/Model/Organization/OwnerCollection.php, src/Kreta/TaskManager/Domain/Model/Organization/ParticipantCollection.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Organization/OrganizationSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Organization/OwnerCollectionSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Organization/ParticipantCollectionSpec.php
* Added owner collection
* Added participant collection
=> Added organization participants collections

src/Kreta/TaskManager/Domain/Model/Project/Project.php, src/Kreta/TaskManager/Domain/Model/Project/ProjectCreated.php, src/Kreta/TaskManager/Domain/Model/Project/ProjectEdited.php, src/Kreta/TaskManager/Domain/Model/Project/ProjectName.php, src/Kreta/TaskManager/Domain/Model/Project/ProjectNameEmptyException.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/ProjectCreatedSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/ProjectEditedSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/ProjectNameEmptyExceptionSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/ProjectNameSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/ProjectSpec.php
=> [Domain] Project aggregate

src/Kreta/TaskManager/Domain/Model/Project/Project.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/ProjectSpec.php
=> Project has to belong to an organization

src/Kreta/TaskManager/Domain/Model/Project/Project.php
=> Fixed missing return types in project

phpspec.yml, src/Kreta/SharedKernel/Tests/Matchers/DomainPublishedMatcher.php, src/Kreta/TaskManager/Domain/Model/Project/Project.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/ProjectSpec.php
=> Added DomainPublishedMatcher and minor refactor of ProjectSpec

src/Kreta/TaskManager/Domain/Model/Project/ProjectName.php
=> Added missing ProjectName property

src/Kreta/TaskManager/Domain/Model/Project/Task/Task.php, src/Kreta/TaskManager/Domain/Model/Project/Task/TaskCreated.php, src/Kreta/TaskManager/Domain/Model/Project/Task/TaskReassigned.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/Task/TaskCreatedSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/Task/TaskReassignedSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/Task/TaskSpec.php
=> Renamed broken references to Participant

src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/Task/TaskSpec.php
=> Added missing typehint in TaskSpec

src/Kreta/TaskManager/Application/Organization/EditOrganizationCommand.php, src/Kreta/TaskManager/Application/Organization/EditOrganizationHandler.php, src/Kreta/TaskManager/Domain/Model/Organization/Member.php, src/Kreta/TaskManager/Domain/Model/Organization/MemberAdded.php, src/Kreta/TaskManager/Domain/Model/Organization/MemberRemoved.php, src/Kreta/TaskManager/Domain/Model/Organization/Organization.php, src/Kreta/TaskManager/Domain/Model/Organization/OrganizationDoesNotExistException.php, src/Kreta/TaskManager/Domain/Model/Organization/OrganizationEdited.php, src/Kreta/TaskManager/Domain/Model/Organization/OwnerAdded.php, src/Kreta/TaskManager/Domain/Model/Organization/OwnerRemoved.php, src/Kreta/TaskManager/Domain/Model/Organization/UnauthorizedEditOrganizationException.php, src/Kreta/TaskManager/Domain/Model/Organization/UnauthorizedRemoveOwnerException.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Application/Organization/EditOrganizationCommandSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Application/Organization/EditOrganizationHandlerSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Organization/MemberAddedSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Organization/MemberRemovedSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Organization/OrganizationDoesNotExistExceptionSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Organization/OrganizationEditedSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Organization/OrganizationSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Organization/OwnerAddedSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Organization/OwnerRemovedSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Organization/UnauthorizedEditOrganizationExceptionSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Organization/UnauthorizedRemoveOwnerExceptionSpec.php
| Fixed tickets | #128
| Doc PR        | none
=> Added edit organization domain logic and its aplication service

src/Kreta/TaskManager/Application/Project/Task/CreateTaskCommand.php, src/Kreta/TaskManager/Application/Project/Task/CreateTaskHandler.php, src/Kreta/TaskManager/Domain/Model/Organization/Organization.php, src/Kreta/TaskManager/Domain/Model/Project/ProjectDoesNotExistException.php, src/Kreta/TaskManager/Domain/Model/Project/ProjectRepository.php, src/Kreta/TaskManager/Domain/Model/Project/Task/Task.php, src/Kreta/TaskManager/Domain/Model/Project/Task/TaskAlreadyExistsException.php, src/Kreta/TaskManager/Domain/Model/Project/Task/TaskAndTaskParentCannotBeTheSameException.php, src/Kreta/TaskManager/Domain/Model/Project/Task/TaskCreated.php, src/Kreta/TaskManager/Domain/Model/Project/Task/TaskCreationNotAllowedException.php, src/Kreta/TaskManager/Domain/Model/Project/Task/TaskDoesNotExistException.php, src/Kreta/TaskManager/Domain/Model/Project/Task/TaskParentDoesNotExistException.php, src/Kreta/TaskManager/Domain/Model/Project/Task/TaskPriority.php, src/Kreta/TaskManager/Domain/Model/Project/Task/TaskPriorityNotAllowedException.php, src/Kreta/TaskManager/Domain/Model/Project/Task/TaskReassigned.php, src/Kreta/TaskManager/Domain/Model/Project/Task/TaskRepository.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Application/Project/Task/CreateTaskCommandSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Application/Project/Task/CreateTaskHandlerSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Organization/OrganizationSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/ProjectDoesNotExistExceptionSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/Task/TaskAlreadyExistsExceptionSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/Task/TaskAndTaskParentCannotBeTheSameExceptionSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/Task/TaskCreatedSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/Task/TaskCreationNotAllowedExceptionSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/Task/TaskDoesNotExistExceptionSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/Task/TaskParentDoesNotExistExceptionSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/Task/TaskPriorityNotAllowedExceptionSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/Task/TaskPrioritySpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/Task/TaskReassignedSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/Task/TaskSpec.php
=> Added Create Task application service

src/Kreta/TaskManager/Application/Project/CreateProjectCommand.php, src/Kreta/TaskManager/Application/Project/CreateProjectHandler.php, src/Kreta/TaskManager/Domain/Model/Project/ProjectAlreadyExists.php, src/Kreta/TaskManager/Domain/Model/Project/ProjectRepository.php, src/Kreta/TaskManager/Domain/Model/Project/UnauthorizedCreateProjectException.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Application/Project/CreateProjectCommandSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Application/Project/CreateProjectHandlerSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/ProjectAlreadyExistsSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/UnauthorizedCreateProjectExceptionSpec.php
=> Added Create Project application service

src/Kreta/TaskManager/Application/Project/Task/EditTaskCommand.php, src/Kreta/TaskManager/Application/Project/Task/EditTaskHandler.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Application/Project/Task/EditTaskCommandSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Application/Project/Task/EditTaskHandlerSpec.php
=> Added task edition application service

src/Kreta/TaskManager/Application/Project/Task/ChangeTaskPriorityCommand.php, src/Kreta/TaskManager/Application/Project/Task/ChangeTaskPriorityHandler.php, src/Kreta/TaskManager/Domain/Model/Project/Task/UnauthorizedTaskActionException.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Application/Project/Task/ChangeTaskPriorityCommandSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Application/Project/Task/ChangeTaskPriorityHandlerSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/Task/UnauthorizedTaskActionExceptionSpec.php
| Fixed tickets | closes #150 
=> Added ChangeTaskPriority application service

src/Kreta/TaskManager/Application/Project/Task/ChangeParentTaskCommand.php, src/Kreta/TaskManager/Application/Project/Task/ChangeParentTaskHandler.php, src/Kreta/TaskManager/Domain/Model/Project/Task/Task.php, src/Kreta/TaskManager/Domain/Model/Project/Task/TaskParentCannotBelongToOtherProjectException.php, src/Kreta/TaskManager/Domain/Model/Project/Task/TaskParentChanged.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Application/Project/Task/ChangeParentTaskCommandSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Application/Project/Task/ChangeParentTaskHandlerSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/Task/TaskParentCannotBelongToOtherProjectExceptionSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/Task/TaskParentChangedSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/Task/TaskSpec.php
=> Added change parent task application service

src/Kreta/TaskManager/Application/Organization/AddOwnerToOrganizationCommand.php, src/Kreta/TaskManager/Application/Organization/AddOwnerToOrganizationHandler.php, src/Kreta/TaskManager/Domain/Model/Organization/MemberIsAlreadyAnOwnerException.php, src/Kreta/TaskManager/Domain/Model/Organization/Organization.php, src/Kreta/TaskManager/Domain/Model/Organization/UnauthorizedOrganizationActionException.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Application/Organization/AddOwnerToOrganizationCommandSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Application/Organization/AddOwnerToOrganizationHandlerSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Organization/MemberIsAlreadyAnOwnerExceptionSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Organization/OrganizationSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Organization/UnauthorizedOrganizationActionExceptionSpec.php
| Bug fix?      |no
| Fixed tickets | #146 
=> Added add owner to organization application service

src/Kreta/TaskManager/Application/Project/Task/ReassignTaskCommand.php, src/Kreta/TaskManager/Application/Project/Task/ReassignTaskHandler.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Application/Project/Task/ReassignTaskCommandSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Application/Project/Task/ReassignTaskHandlerSpec.php
| Fixed tickets | closes #152 
=> Reassign task handler added

src/Kreta/TaskManager/Application/Project/Task/ChangeTaskPriorityHandler.php, src/Kreta/TaskManager/Application/Project/Task/ChangeTaskProgressCommand.php, src/Kreta/TaskManager/Application/Project/Task/ChangeTaskProgressHandler.php, src/Kreta/TaskManager/Domain/Model/Project/Task/TaskProgress.php, src/Kreta/TaskManager/Domain/Model/Project/Task/TaskProgressNotAllowedException.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Application/Project/Task/ChangeTaskPriorityHandlerSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Application/Project/Task/ChangeTaskProgressCommandSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Application/Project/Task/ChangeTaskProgressHandlerSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/Task/TaskProgressNotAllowedExceptionSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/Task/TaskProgressSpec.php
=> Change task progress

src/Kreta/TaskManager/Application/Project/EditProjectCommand.php, src/Kreta/TaskManager/Application/Project/EditProjectHandler.php, src/Kreta/TaskManager/Domain/Model/Project/UnauthorizedProjectActionException.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Application/Project/EditProjectCommandSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Application/Project/EditProjectHandlerSpec.php, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/UnauthorizedProjectActionExceptionSpec.php
=> Added edit project application service

app/config/config.yml, src/AppBundle/Command/ProjectFixturesCommand.php, src/Kreta/TaskManager/Domain/Model/Project/Project.php, src/Kreta/TaskManager/Infrastructure/Persistence/Doctrine/DBAL/Project/Types/ProjectIdType.php, src/Kreta/TaskManager/Infrastructure/Persistence/Doctrine/ORM/Project/Mapping/Kreta.TaskManager.Domain.Model.Project.Project.dcm.xml, src/Kreta/TaskManager/Infrastructure/Persistence/Doctrine/ORM/Project/Mapping/Kreta.TaskManager.Domain.Model.Project.ProjectName.dcm.xml, src/Kreta/TaskManager/Infrastructure/Persistence/Doctrine/ORM/Project/SymfonyMapping/Project.orm.xml, src/Kreta/TaskManager/Infrastructure/Persistence/Doctrine/ORM/Project/SymfonyMapping/ProjectName.orm.xml, src/Kreta/TaskManager/Tests/Spec/Kreta/TaskManager/Domain/Model/Project/ProjectSpec.php
| Bug fix?      |no
| Fixed tickets | #164
=> Added doctrine mappings for Project aggregate

etc/docker/.env.dist, etc/docker/.gitignore, etc/docker/README.md, etc/docker/docker-compose.yml, etc/docker/elk/logstash/logstash.conf, etc/docker/elk/logstash/patterns/default.conf, etc/docker/elk/logstash/patterns/nginx.conf, etc/docker/elk/logstash/patterns/symfony.conf, etc/docker/nginx/Dockerfile, etc/docker/nginx/nginx.conf, etc/docker/nginx/symfony.conf, etc/docker/php7-fpm/Dockerfile
Added docker with the following containers:
* Nginx
* MySQL
* PHP7-FPM
* Elastic-Logstash-Kibana (ELK)
* Redis
* RabbitMQ
* Data volumes (for db and app data)
=> Docker is here!!

etc/bash/IdentityAccess/generate_ssh_keys.sh
=> Added script that automatizes the JWT ssh keys generation

etc/docker/nginx/symfony.conf, etc/docker/php7-fpm/Dockerfile
=> Adapted docker to new paths and added missing php extension

TaskManager/composer.json, TaskManager/composer.lock
=> Upgraded query bus bundle to stable version

IdentityAccess/composer.json, SharedKernel/composer.json, TaskManager/composer.json, TaskManager/composer.lock, etc/bash/publish_shared_kernel.sh
=> Updated composers to adapt the new shared kernel publication

CompositeUi/src/actions/User.js, CompositeUi/src/api/Security.js, CompositeUi/src/reducers/Notification.js, CompositeUi/src/reducers/User.js, CompositeUi/src/views/page/Login.js
=> Show error message when a user fails a login

CompositeUi/.gitignore, CompositeUi/package.json, CompositeUi/src/__mocks__/fileMock.js, CompositeUi/src/__mocks__/localStorage.js, CompositeUi/src/__mocks__/mockStore.js, CompositeUi/src/__mocks__/styleMock.js, CompositeUi/src/__tests__/actions/CurrentProjectSpec.js, CompositeUi/src/__tests__/actions/MainMenu.js, CompositeUi/src/__tests__/actions/UserSpec.js, CompositeUi/src/actions/User.js, CompositeUi/src/api/Security.js, CompositeUi/src/api/__mocks__/Security.js, CompositeUi/src/views/component/Button.js, CompositeUi/src/views/component/DashboardWidget.js, CompositeUi/src/views/component/SectionHeader.js, CompositeUi/src/views/component/__tests__/Button.js, CompositeUi/src/views/component/__tests__/DashboardWidget.js, CompositeUi/yarn.lock
=> Configured test environment for CompositeUI and added some sample tests

.travis.yml, CompositeUi/.gitignore, CompositeUi/package.json, etc/bash/install.sh, etc/bash/tests.sh
=> Added composite ui to travis configuration

CompositeUi/src/views/component/FormInput.js, CompositeUi/src/views/component/__tests__/FormInput.js, CompositeUi/src/views/form/IssueNew.js
=> Use multiline input in new issue form for description

etc/bash/docker.sh, etc/docker/docker-compose.yml, etc/docker/nginx/Dockerfile, etc/docker/nginx/compositeui.template, etc/docker/nginx/identityaccess.template, etc/docker/nginx/nginx.conf, etc/docker/nginx/server_run.sh, etc/docker/nginx/taskmanager.template
=> Use .env variables to define nginx server names in Docker

etc/bash/docker.sh
=> Run always migrations to ensure database is correct when running docker

IdentityAccess/composer.json, IdentityAccess/composer.lock, IdentityAccess/parameters.yml.dist, IdentityAccess/src/Kreta/IdentityAccess/Infrastructure/Symfony/Framework/config/services/event_subscribers.yml, IdentityAccess/src/Kreta/IdentityAccess/Infrastructure/Symfony/Framework/config/services/url_generators.yml, TaskManager/composer.json, TaskManager/composer.lock, TaskManager/parameters.yml.dist, TaskManager/src/Kreta/TaskManager/Infrastructure/Symfony/Framework/config/config.yml, etc/docker/docker-compose.yml
This PR also fixes issues with Gmail default config and some minor configuration issues.
Introduces a constraint in Symfony ~3.2 due to the use of env config paramaters.
=> Read from env variables in parameters.yml

etc/bash/docker.sh
=> Keep execution when running rabbit consumer on docker initialization

CompositeUi/src/api/rest/User/Register.js, IdentityAccess/src/Kreta/IdentityAccess/Infrastructure/Serialization/NameResolver.php, IdentityAccess/src/Kreta/IdentityAccess/Infrastructure/Symfony/Form/Type/EditProfileType.php, IdentityAccess/src/Kreta/IdentityAccess/Infrastructure/Symfony/Framework/config/config.yml, IdentityAccess/src/Kreta/IdentityAccess/Infrastructure/Symfony/Framework/config/routing.yml, IdentityAccess/src/Kreta/IdentityAccess/Infrastructure/Symfony/Framework/config/services/command_bus.yml, IdentityAccess/src/Kreta/IdentityAccess/Infrastructure/Symfony/Framework/config/services/command_handlers.yml, IdentityAccess/src/Kreta/IdentityAccess/Infrastructure/Symfony/Framework/config/services/http_actions.yml, IdentityAccess/src/Kreta/IdentityAccess/Infrastructure/Symfony/HttpAction/EnableAction.php
This action now has the SimpleBus command bus (not the bengoruser simple command bus)
| Doc PR        | reference to the documentation PR, if any
=> Extracted the enable action from BenGorUserBundle to kreta.

CompositeUi/src/scss/components/_card-extended.scss, CompositeUi/src/scss/components/_card-minimal.scss, CompositeUi/src/views/component/CardExtended.js, CompositeUi/src/views/component/CardMinimal.js
This will replace UserPreview and ResourcePreview components that will be deprecated and removed once all views are refactored.
=> Created content agnostic Card components 

CompositeUi/src/scss/components/_page-header.scss, CompositeUi/src/views/component/PageHeader.js
Simplified the component a lot
=> Refactored Page Header component

CompositeUi/src/scss/layout/_content.scss, CompositeUi/src/views/layout/ContentMiddleLayout.js, CompositeUi/src/views/page/Login.js, CompositeUi/src/views/page/Register.js, CompositeUi/src/views/page/RequestResetPassword.js, CompositeUi/src/views/page/ResetPassword.js, CompositeUi/src/views/page/organization/New.js, CompositeUi/src/views/page/profile/Edit.js, CompositeUi/src/views/page/project/New.js, CompositeUi/src/views/page/task/New.js
Also added a flag to center the content if necessary
=> Position content on top by default in layout

IdentityAccess/composer.lock, IdentityAccess/src/Kreta/IdentityAccess/Infrastructure/Persistence/Doctrine/ORM/User/SymfonyMapping/User.orm.xml
=> Fixed the bug occurred when the user related image is null

CompositeUi/src/views/page/Dashboard.js
=> Fixed dashboard search bar unexpected crashes

CompositeUi/.eslintrc.js, CompositeUi/config/env.js, CompositeUi/src/api/graphql/GraphQl.js
=> __DEV__ flag to code easily anything only for development env

TaskManager/src/Kreta/TaskManager/Application/Command/Organization/AddOrganizationMemberToOrganizationHandler.php, TaskManager/src/Kreta/TaskManager/Application/Command/Organization/AddOwnerToOrganizationHandler.php, TaskManager/tests/Spec/Kreta/TaskManager/Application/Command/Organization/AddOrganizationMemberToOrganizationHandlerSpec.php, TaskManager/tests/Spec/Kreta/TaskManager/Application/Command/Organization/AddOwnerToOrganizationHandlerSpec.php
| Fixed tickets | #179 
| Doc PR        | reference to the documentation PR, if any
=> Validated against db the user existence when adding to organization

CompositeUi/src/views/page/task/New.js
=> Wait until currentProject is loaded to show task creation page

CompositeUi/src/scss/components/_card-extended.scss, CompositeUi/src/views/page/organization/Show.js
Fixed also behavior of card-extended below Link
=> Added missing project links in organization page

CompositeUi/src/views/component/Button.js, CompositeUi/src/views/component/Grid.js
- Removed onClick from button (is react's event and is not used specially in button)
- Use spread operator to clean Grid component a little bit
=> Minor refactor in couple components

CompositeUi/src/scss/views/page/_dashboard.scss, CompositeUi/src/views/page/Dashboard.js
- Removed deprecated ResourcePreview
- Moved content inside DashboardWidget
- New look using CardMinimal and CardExtended for org and projects
=> Refactored Dashboard page

SharedKernel/src/Kreta/SharedKernel/Application/CommandBus.php, SharedKernel/src/Kreta/SharedKernel/Application/QueryBus.php, SharedKernel/src/Kreta/SharedKernel/Domain/Event/AsyncEventSubscriber.php, SharedKernel/src/Kreta/SharedKernel/Domain/Event/EventSubscriber.php, SharedKernel/src/Kreta/SharedKernel/Domain/Model/AggregateDoesNotExistException.php, SharedKernel/src/Kreta/SharedKernel/Domain/Model/AggregateRoot.php, SharedKernel/src/Kreta/SharedKernel/Domain/Model/AsyncDomainEventValueDoesNotExistException.php, SharedKernel/src/Kreta/SharedKernel/Domain/Model/Collection.php, SharedKernel/src/Kreta/SharedKernel/Domain/Model/Identity/BaseId.php, SharedKernel/src/Kreta/SharedKernel/Domain/Model/Identity/Id.php, SharedKernel/src/Kreta/SharedKernel/Event/AsyncEvent.php, SharedKernel/src/Kreta/SharedKernel/Event/EventStore.php, SharedKernel/src/Kreta/SharedKernel/Infrastructure/Application/SimpleBus/SimpleBusCommandBus.php, SharedKernel/src/Kreta/SharedKernel/Infrastructure/Application/SimpleBus/SimpleBusQueryBus.php, SharedKernel/src/Kreta/SharedKernel/Infrastructure/Event/SimpleBus/EventRecorder/Doctrine/ORM/AggregateRootEventRecorder.php, SharedKernel/src/Kreta/SharedKernel/Infrastructure/Persistence/InMemory/EventStore/InMemoryEventStore.php, SharedKernel/src/Kreta/SharedKernel/Infrastructure/Serialization/SimpleBus/SimpleBusAsyncEventSerializer.php, SharedKernel/src/Kreta/SharedKernel/Serialization/AsyncEventSerializer.php, SharedKernel/tests/Double/Domain/Model/Identity/IdStub.php, SharedKernel/tests/Spec/Kreta/SharedKernel/Domain/Model/Identity/IdSpec.php, SharedKernel/tests/Spec/Kreta/SharedKernel/Infrastructure/Persistence/InMemory/EventStore/InMemoryEventStoreSpec.php
=> Added PHP7.1 typehints in SharedKernel

CompositeUi/src/actions/CurrentProject.js, CompositeUi/src/helpers/UserInjector.js, CompositeUi/src/views/component/TaskPreview.js
Added also some example task to temporary current project action
=> Extracted identity access user injection in CompositeUi

TaskManager/src/Kreta/TaskManager/Application/Query/Project/ProjectOfSlugHandler.php, TaskManager/src/Kreta/TaskManager/Application/Query/Project/ProjectOfSlugQuery.php, TaskManager/src/Kreta/TaskManager/Domain/Model/Project/ProjectRepository.php, TaskManager/src/Kreta/TaskManager/Domain/Model/Project/ProjectSpecificationFactory.php, TaskManager/src/Kreta/TaskManager/Infrastructure/Persistence/Doctrine/DBAL/Project/Task/Types/TaskIdType.php, TaskManager/src/Kreta/TaskManager/Infrastructure/Persistence/Doctrine/ORM/Project/DoctrineORMBySlugSpecification.php, TaskManager/src/Kreta/TaskManager/Infrastructure/Persistence/Doctrine/ORM/Project/DoctrineORMProjectRepository.php, TaskManager/src/Kreta/TaskManager/Infrastructure/Persistence/Doctrine/ORM/Project/DoctrineORMProjectSpecificationFactory.php, TaskManager/src/Kreta/TaskManager/Infrastructure/Symfony/Bundle/Resources/config/graphql/Query.types.yml, TaskManager/src/Kreta/TaskManager/Infrastructure/Symfony/Framework/config/services/graph_ql/queries/project.yml, TaskManager/src/Kreta/TaskManager/Infrastructure/Symfony/Framework/config/services/graph_ql/queries/task.yml, TaskManager/src/Kreta/TaskManager/Infrastructure/Symfony/Framework/config/services/query_handlers/project.yml, TaskManager/src/Kreta/TaskManager/Infrastructure/Symfony/GraphQl/Query/Project/ProjectResolver.php, TaskManager/tests/Spec/Kreta/TaskManager/Application/Query/Project/ProjectOfSlugHandlerSpec.php, TaskManager/tests/Spec/Kreta/TaskManager/Application/Query/Project/ProjectOfSlugQuerySpec.php
=> Added project by slug graphql endpoint

TaskManager/src/Kreta/TaskManager/Application/Command/Project/Task/CreateTaskCommand.php, TaskManager/src/Kreta/TaskManager/Infrastructure/Symfony/Bundle/Resources/config/graphql/Mutation.types.yml, TaskManager/src/Kreta/TaskManager/Infrastructure/Symfony/Bundle/Resources/config/graphql/relay/CreateTaskInput.types.yml, TaskManager/src/Kreta/TaskManager/Infrastructure/Symfony/Bundle/Resources/config/graphql/relay/CreateTaskPayload.types.yml, TaskManager/src/Kreta/TaskManager/Infrastructure/Symfony/Framework/config/services/graph_ql/mutations/task.yml, TaskManager/src/Kreta/TaskManager/Infrastructure/Symfony/GraphQl/Mutation/Project/Task/CreateTaskMutation.php, TaskManager/tests/Spec/Kreta/TaskManager/Application/Command/Project/Task/CreateTaskCommandSpec.php
=> Added create task graphql mutation

TaskManager/src/Kreta/TaskManager/Application/Command/Project/CreateProjectHandler.php, TaskManager/src/Kreta/TaskManager/Domain/Model/Organization/OrganizationRepository.php, TaskManager/src/Kreta/TaskManager/Domain/Model/Project/ProjectAlreadyExists.php, TaskManager/src/Kreta/TaskManager/Domain/Model/Project/ProjectRepository.php, TaskManager/src/Kreta/TaskManager/Infrastructure/Persistence/Doctrine/ORM/Organization/DoctrineORMOrganizationRepository.php, TaskManager/src/Kreta/TaskManager/Infrastructure/Persistence/Doctrine/ORM/Project/DoctrineORMProjectRepository.php, TaskManager/tests/Spec/Kreta/TaskManager/Application/Command/Project/CreateProjectHandlerSpec.php, TaskManager/tests/Spec/Kreta/TaskManager/Domain/Model/Project/ProjectAlreadyExistsSpec.php
=> Made project slug unique by organization

CompositeUi/src/actions/CurrentProject.js, CompositeUi/src/api/graphql/mutation/CreateTaskMutationRequest.js, CompositeUi/src/api/graphql/query/ProjectQueryRequest.js, CompositeUi/src/reducers/CurrentProject.js, CompositeUi/src/views/component/TaskPreview.js, CompositeUi/src/views/page/project/TaskList.js
=> Fixes and minor improvements of task list

IdentityAccess/src/Kreta/IdentityAccess/Infrastructure/Symfony/Command/UserFixturesCommand.php, TaskManager/src/Kreta/TaskManager/Infrastructure/Symfony/Command/OrganizationFixturesCommand.php, TaskManager/src/Kreta/TaskManager/Infrastructure/Symfony/Command/ProjectFixturesCommand.php, TaskManager/src/Kreta/TaskManager/Infrastructure/Symfony/Command/TaskFixturesCommand.php, TaskManager/src/Kreta/TaskManager/Infrastructure/Symfony/Command/UserFixturesCommand.php
Added progress bar, avoid annoying Entity Manager is Closed Doctrine exception and load more dummy data
| Doc PR        | #288
=> Improvements in the fixture commands

CompositeUi/src/actions/CurrentProject.js
=> Fixed task users serialization bug when the task filter is changed

TaskManager/src/Kreta/TaskManager/Infrastructure/Symfony/Bundle/Resources/config/graphql/Mutation.types.yml, TaskManager/src/Kreta/TaskManager/Infrastructure/Symfony/Bundle/Resources/config/graphql/relay/EditProjectInput.types.yml, TaskManager/src/Kreta/TaskManager/Infrastructure/Symfony/Bundle/Resources/config/graphql/relay/EditProjectPayload.types.yml, TaskManager/src/Kreta/TaskManager/Infrastructure/Symfony/Framework/config/services/graph_ql/mutations/project.yml, TaskManager/src/Kreta/TaskManager/Infrastructure/Symfony/GraphQl/Mutation/Project/EditProjectMutation.php
=> Added edit project graphql mutation

CompositeUi/src/actions/Profile.js
Fixes #311 
| Fixed tickets | fixes #311 
=> Redirect the user to login page when 401 is returned by fetch profile

CompositeUi/src/Routes.js
Moved profile route up to prioritize it over /:organization
=> Fixed profile page unable to be accessed

CompositeUi/src/reducers/CurrentProject.js, CompositeUi/src/views/layout/Base.js, CompositeUi/src/views/page/project/TaskList.js
=> Fixed assignee filter and minor refactor

CompositeUi/src/views/form/ProfileEdit.js, CompositeUi/src/views/layout/Base.js
=> Fixed bug related with the profile loading

IdentityAccess/src/Kreta/IdentityAccess/Application/DataTransformer/UserDTODataTransformer.php, IdentityAccess/src/Kreta/IdentityAccess/Application/DataTransformer/UserPublicDTODataTransformer.php, IdentityAccess/src/Kreta/IdentityAccess/Infrastructure/Symfony/Framework/config/services/data_transformers.yml, IdentityAccess/src/Kreta/IdentityAccess/Infrastructure/Symfony/Framework/config/services/query_handlers.yml, IdentityAccess/tests/Spec/Kreta/IdentityAccess/Application/DataTransformer/UserPublicDTODataTransformerSpec.php
=> Remove sensible information from serialization in the user dto

CompositeUi/src/reducers/CurrentOrganization.js, CompositeUi/src/reducers/CurrentProject.js, CompositeUi/src/reducers/Organization.js, CompositeUi/src/reducers/Profile.js, CompositeUi/src/reducers/User.js, CompositeUi/src/scss/components/_button.scss, CompositeUi/src/views/form/Login.js, CompositeUi/src/views/form/OrganizationNew.js, CompositeUi/src/views/form/ProfileEdit.js, CompositeUi/src/views/form/ProjectEdit.js, CompositeUi/src/views/form/ProjectNew.js, CompositeUi/src/views/form/Register.js, CompositeUi/src/views/form/RequestResetPassword.js, CompositeUi/src/views/form/TaskEdit.js, CompositeUi/src/views/form/TaskNew.js, CompositeUi/src/views/page/Login.js
=> Prevent submitting the form twice disabling the button

docs/usage_bash_scripts_and_cli_commands.md
Fixed "context" typos and some basic English stuff
| Bug fix?      |no
| New feature?  |no
| Doc PR        | reference to the documentation PR, if any
=> Fixed typos

CompositeUi/src/Routes.js, CompositeUi/src/actions/CurrentOrganization.js, CompositeUi/src/views/page/organization/AddMember.js, CompositeUi/src/views/page/organization/Show.js
- Fixed issues adding members
- Refactored to show add_members page by route
- Added icons to buttons
- Fetch potential members on component mount
- Added message when potential members not found
Closes #352
=> Fixes and refactor related to add member

CompositeUi/src/actions/User.js
=> Added invalid credentials messages on login

IdentityAccess/parameters.yml.dist, IdentityAccess/src/Kreta/IdentityAccess/Infrastructure/Symfony/Framework/config/config.yml
=> Made manageable the harcoded identity access scheme from url

.travis.yml, IdentityAccess/composer.json, IdentityAccess/composer.lock, IdentityAccess/etc/bash/install_test_env.sh, IdentityAccess/src/Kreta/IdentityAccess/Infrastructure/Symfony/Framework/config/config_dev.yml, Notifier/composer.json, Notifier/composer.lock, Notifier/src/Kreta/Notifier/Infrastructure/Symfony/Framework/config/config_dev.yml, TaskManager/composer.json, TaskManager/composer.lock, TaskManager/src/Kreta/TaskManager/Infrastructure/Symfony/Framework/config/config_dev.yml, etc/bash/install_test_env.sh
=> Updated deps fixed according shared kernel version per BC

TaskManager/src/Kreta/TaskManager/Application/Command/Project/Task/CreateTaskHandler.php, TaskManager/src/Kreta/TaskManager/Infrastructure/Symfony/GraphQl/Mutation/Project/Task/CreateTaskMutation.php, TaskManager/src/Kreta/TaskManager/Infrastructure/Symfony/GraphQl/Query/Organization/MemberResolver.php, TaskManager/tests/Integration/Expected/Responses/graphql/mutation/project/task/create_task.json, TaskManager/tests/Integration/Expected/Responses/graphql/mutation/project/task/create_task_with_nonexistent_parent.json, TaskManager/tests/Integration/Expected/Responses/graphql/mutation/project/task/create_task_with_nonexistent_project.json, TaskManager/tests/Integration/Expected/Responses/graphql/mutation/project/task/create_task_with_not_member_assignee.json, TaskManager/tests/Integration/Expected/Responses/graphql/mutation/project/task/create_task_with_not_member_creator.json, TaskManager/tests/Integration/Expected/Responses/graphql/mutation/project/task/create_task_with_parent.json, TaskManager/tests/Integration/Expected/Responses/graphql/query/project/task/tasks_of_user2.json, TaskManager/tests/Integration/GraphQl/Mutation/Project/Task/CreateTaskMutationTest.php, TaskManager/tests/Integration/GraphQl/Query/Project/ProjectResolverTest.php, TaskManager/tests/Integration/GraphQl/Query/Project/Task/TaskResolverTest.php, TaskManager/tests/Integration/GraphQl/Query/Project/Task/TasksResolverTest.php
=> Added create task mutation integration test

IdentityAccess/src/Kreta/IdentityAccess/Application/Command/EditProfileHandler.php, IdentityAccess/src/Kreta/IdentityAccess/Domain/Model/User/Username.php, IdentityAccess/src/Kreta/IdentityAccess/Infrastructure/Persistence/Doctrine/Migrations/Version20161101130554.php, IdentityAccess/src/Kreta/IdentityAccess/Infrastructure/Persistence/Doctrine/Migrations/Version20170213183245.php, IdentityAccess/src/Kreta/IdentityAccess/Infrastructure/Persistence/Doctrine/Migrations/Version20170731164211.php, IdentityAccess/src/Kreta/IdentityAccess/Infrastructure/Persistence/Doctrine/ORM/User/SymfonyMapping/Username.orm.xml, IdentityAccess/tests/Spec/Kreta/IdentityAccess/Application/Command/EditProfileHandlerSpec.php, IdentityAccess/tests/Spec/Kreta/IdentityAccess/Domain/Model/User/UsernameAlreadyExistsExceptionSpec.php, IdentityAccess/tests/Spec/Kreta/IdentityAccess/Domain/Model/User/UsernameSpec.php
| Fixed tickets | Closes #387 
=> Removed 20 max length restriction for usernames that are created from email

README.md
| Fixed tickets | Closes #386 
=> Updated auto invitation slack link replacing outdated slackinvite service for slackin

CompositeUi/public/index.html, CompositeUi/src/actions/Dashboard.js, CompositeUi/src/actions/Projects.js, CompositeUi/src/api/graphql/query/ProjectsQueryRequest.js, CompositeUi/src/api/graphql/query/TasksQueryRequest.js, CompositeUi/src/reducers/Dashboard.js, CompositeUi/src/scss/base/_common.scss, CompositeUi/src/scss/components/_button.scss, CompositeUi/src/scss/components/_card-extended.scss, CompositeUi/src/scss/components/_dashboard-widget.scss, CompositeUi/src/scss/components/_filter.scss, CompositeUi/src/scss/components/_link-inline.scss, CompositeUi/src/scss/components/_page-header.scss, CompositeUi/src/scss/components/_section-header.scss, CompositeUi/src/scss/components/_table.scss, CompositeUi/src/scss/variables/_typography.scss, CompositeUi/src/scss/views/page/_dashboard.scss, CompositeUi/src/scss/views/page/organization/_show.scss, CompositeUi/src/views/component/DashboardWidget.js, CompositeUi/src/views/component/Table.js, CompositeUi/src/views/component/__tests__/Advice.js, CompositeUi/src/views/composition/AssignedTasksDashboardWidget.js, CompositeUi/src/views/composition/LastUpdatedProjectsDashboardWidget.js, CompositeUi/src/views/composition/MyOrganizationsDashboardWidget.js, CompositeUi/src/views/page/Dashboard.js, TaskManager/src/Kreta/TaskManager/Domain/Model/Organization/OrganizationSpecificationFactory.php, TaskManager/src/Kreta/TaskManager/Infrastructure/Persistence/Doctrine/ORM/Organization/DoctrineORMFilterableSpecification.php, TaskManager/src/Kreta/TaskManager/Infrastructure/Persistence/Doctrine/ORM/Organization/DoctrineORMOrganizationSpecificationFactory.php
=> Improved most of parts of scss and initial refactor about dashboard view

.travis.yml, CompositeUi/yarn.lock, IdentityAccess/src/Kreta/IdentityAccess/Infrastructure/Symfony/Framework/config/config_test.yml, README.md, TaskManager/src/Kreta/TaskManager/Infrastructure/Symfony/Framework/config/config_test.yml, TaskManager/tests/Integration/GraphQl/Mutation/Project/Task/CreateTaskMutationTest.php, appveyor.yml
=> CI for Windows
